describe('D3Task1', () => {
    it('upload document in the document section', () => {
      cy.visit('https://dev.devmobo.com/login')
      cy.get('#email').type('unknown1@gmail.com')
      cy.get('#password').type('onepiece')
      cy.contains('Log in').click()
      cy.get(':nth-child(6) > .nav-link').click()
      cy.contains('Add Contacts').click()
      cy.get('tbody > :nth-child(2) > :nth-child(1)').type('Cierra Vega')
      cy.get('tbody > :nth-child(2) > :nth-child(2)').type('AAAA')
      cy.get('tbody > :nth-child(2) > :nth-child(3)').type('random1@gmail.com')
      cy.get('tbody > :nth-child(2) > :nth-child(4)').type('4842 Masonic Hill Road')
      cy.get('tbody > :nth-child(2) > :nth-child(5)').type('Little Rock')
      cy.get('tbody > :nth-child(2) > :nth-child(6)').type('1234')
      cy.get('tbody > :nth-child(2) > :nth-child(7)').type('Arkansas')
      cy.get('tbody > :nth-child(2) > :nth-child(8)').type('72211')
      cy.get('tbody > :nth-child(2) > :nth-child(9)').type('501-456-3662')

      cy.get('tbody > :nth-child(3) > :nth-child(1)').type('Alden Cantrell')
      cy.get('tbody > :nth-child(3) > :nth-child(2)').type('BBBB')
      cy.get('tbody > :nth-child(3) > :nth-child(3)').type('random2@gmail.com')
      cy.get('tbody > :nth-child(3) > :nth-child(4)').type('2231 Irving Place')
      cy.get('tbody > :nth-child(3) > :nth-child(5)').type('New York')
      cy.get('tbody > :nth-child(3) > :nth-child(6)').type('1234')
      cy.get('tbody > :nth-child(3) > :nth-child(7)').type('New York')
      cy.get('tbody > :nth-child(3) > :nth-child(8)').type('10011')
      cy.get('tbody > :nth-child(3) > :nth-child(9)').type('631-993-0021')

      cy.get('tbody > :nth-child(4) > :nth-child(1)').type('Kierra Gentry')
      cy.get('tbody > :nth-child(4) > :nth-child(2)').type('CCCC')
      cy.get('tbody > :nth-child(4) > :nth-child(3)').type('random3@gmail.com')
      cy.get('tbody > :nth-child(4) > :nth-child(4)').type('2441 Brooklyn Street')
      cy.get('tbody > :nth-child(4) > :nth-child(5)').type('Pulaski')
      cy.get('tbody > :nth-child(4) > :nth-child(6)').type('1234')
      cy.get('tbody > :nth-child(4) > :nth-child(7)').type('Virginia')
      cy.get('tbody > :nth-child(4) > :nth-child(8)').type('24301')
      cy.get('tbody > :nth-child(4) > :nth-child(9)').type('540-994-8289')

      cy.get('tbody > :nth-child(5) > :nth-child(1)').type('Pierre Cox')
      cy.get('tbody > :nth-child(5) > :nth-child(2)').type('DDDD')
      cy.get('tbody > :nth-child(5) > :nth-child(3)').type('random4@gmail.com')
      cy.get('tbody > :nth-child(5) > :nth-child(4)').type('687 Oral Lake Road')
      cy.get('tbody > :nth-child(5) > :nth-child(5)').type('Golden Valley')
      cy.get('tbody > :nth-child(5) > :nth-child(6)').type('1234')
      cy.get('tbody > :nth-child(5) > :nth-child(7)').type('Minnesota')
      cy.get('tbody > :nth-child(5) > :nth-child(8)').type(' 55427')
      cy.get('tbody > :nth-child(5) > :nth-child(9)').type('952-542-0040')

      cy.get('tbody > :nth-child(6) > :nth-child(1)').type('Thomas Crane')
      cy.get('tbody > :nth-child(6) > :nth-child(2)').type('EEEE')
      cy.get('tbody > :nth-child(6) > :nth-child(3)').type('random5@gmail.com')
      cy.get('tbody > :nth-child(6) > :nth-child(4)').type('4459 Peck Street')
      cy.get('tbody > :nth-child(6) > :nth-child(5)').type('Dover')
      cy.get('tbody > :nth-child(6) > :nth-child(6)').type('1234')
      cy.get('tbody > :nth-child(6) > :nth-child(7)').type('New Hampshire')
      cy.get('tbody > :nth-child(6) > :nth-child(8)').type('03820')
      cy.get('tbody > :nth-child(6) > :nth-child(9)').type('603-862-3929')
      cy.get('[style="margin-left: 10px;"]').click()

      cy.get('tbody > :nth-child(7) > :nth-child(1)').type('Miranda Shaffer')
      cy.get('tbody > :nth-child(7) > :nth-child(2)').type('FFFF')
      cy.get('tbody > :nth-child(7) > :nth-child(3)').type('random6@gmail.com')
      cy.get('tbody > :nth-child(7) > :nth-child(4)').type('1840 Dovetail Drive')
      cy.get('tbody > :nth-child(7) > :nth-child(5)').type('Hickory Hills')
      cy.get('tbody > :nth-child(7) > :nth-child(6)').type('1234')
      cy.get('tbody > :nth-child(7) > :nth-child(7)').type('Illinois')
      cy.get('tbody > :nth-child(7) > :nth-child(8)').type('60457')
      cy.get('tbody > :nth-child(7) > :nth-child(9)').type('847-308-2277') 
      cy.get('[style="margin-left: 10px;"]').click()

      cy.get('tbody > :nth-child(8) > :nth-child(1)').type('Bradyn Kramer')
      cy.get('tbody > :nth-child(8) > :nth-child(2)').type('GGGG')
      cy.get('tbody > :nth-child(8) > :nth-child(3)').type('random7@gmail.com')
      cy.get('tbody > :nth-child(8) > :nth-child(4)').type('2016 Hall Place')
      cy.get('tbody > :nth-child(8) > :nth-child(5)').type('Linden')
      cy.get('tbody > :nth-child(8) > :nth-child(6)').type('1234')
      cy.get('tbody > :nth-child(8) > :nth-child(7)').type('Texas')
      cy.get('tbody > :nth-child(8) > :nth-child(8)').type('75563')
      cy.get('tbody > :nth-child(8) > :nth-child(9)').type('903-756-5098')
      cy.get('[style="margin-left: 10px;"]').click()

      cy.get('tbody > :nth-child(9) > :nth-child(1)').type('Alvaro Mcgee')
      cy.get('tbody > :nth-child(9) > :nth-child(2)').type('HHHH')
      cy.get('tbody > :nth-child(9) > :nth-child(3)').type('random8@gmail.com')
      cy.get('tbody > :nth-child(9) > :nth-child(4)').type('3774 Dye Street')
      cy.get('tbody > :nth-child(9) > :nth-child(5)').type('Phoenix')
      cy.get('tbody > :nth-child(9) > :nth-child(6)').type('1234')
      cy.get('tbody > :nth-child(9) > :nth-child(7)').type('Arizona')
      cy.get('tbody > :nth-child(9) > :nth-child(8)').type('85016')
      cy.get('tbody > :nth-child(9) > :nth-child(9)').type('480-707-5045')
      cy.get('[style="margin-left: 10px;"]').click()

      cy.get('tbody > :nth-child(10) > :nth-child(1)').type('Lyric Williams')
      cy.get('tbody > :nth-child(10) > :nth-child(2)').type('IIII')
      cy.get('tbody > :nth-child(10) > :nth-child(3)').type('random9@gmail.com')
      cy.get('tbody > :nth-child(10) > :nth-child(4)').type('2089 Franklee Lane')
      cy.get('tbody > :nth-child(10) > :nth-child(5)').type('Tecumseh')
      cy.get('tbody > :nth-child(10) > :nth-child(6)').type('1234')
      cy.get('tbody > :nth-child(10) > :nth-child(7)').type('Kansas')
      cy.get('tbody > :nth-child(10) > :nth-child(8)').type('66542')
      cy.get('tbody > :nth-child(10) > :nth-child(9)').type('484-601-8452')
      cy.get('[style="margin-left: 10px;"]').click()


      cy.get('tbody > :nth-child(11) > :nth-child(1)').type('Lillianna Mora')
      cy.get('tbody > :nth-child(11) > :nth-child(2)').type('JJJJ')
      cy.get('tbody > :nth-child(11) > :nth-child(3)').type('random10@gmail.com')
      cy.get('tbody > :nth-child(11) > :nth-child(4)').type('1476 Sycamore Road')
      cy.get('tbody > :nth-child(11) > :nth-child(5)').type('Oregon')
      cy.get('tbody > :nth-child(11) > :nth-child(6)').type('1234')
      cy.get('tbody > :nth-child(11) > :nth-child(7)').type('Grants Pass')
      cy.get('tbody > :nth-child(11) > :nth-child(8)').type('97526')
      cy.get('tbody > :nth-child(11) > :nth-child(9)').type('541-471-1683')
      cy.contains('Save').click({multiple: true})




    })
})